const llm = require('./llm');

const generationSystemPrompt = `You are a technical writer. Given a conversation transcript between an AI interviewer and a client,
generate a structured project intake document in the exact markdown format specified below.

Synthesize the information — don't just copy/paste raw answers. Clean up spoken language into
clear written descriptions. Organize scattered information logically. Fill in implied details.

OUTPUT FORMAT (follow exactly):

# Project Intake: [Client Name] — [Date]

> Voice intake completed in [X] minutes ([Y] conversation turns)

---

## FEATURE

### Vision
[Synthesized from the full conversation — what they want to build, in clear prose]

### Problem & Users
[Who uses it, what problem it solves, why it matters — synthesized, not just pasted]

### Core Capabilities
[The must-have features, organized and described clearly]

### User Journey
[Step-by-step walkthrough of a typical user interaction]

---

## DESIGN & EXPERIENCE

### Look & Feel
[Visual style, mood, personality — everything design-related from the conversation]

---

## DEPENDENCIES & INTEGRATIONS

### External Systems
[Tools, services, platforms it connects to — or "None identified" if not applicable]

### Scale & Performance
[Expected users, growth expectations]

---

## OTHER CONSIDERATIONS
[Timeline, budget, platform preferences, dealbreakers, anything else mentioned]

---

## Full Conversation Transcript

[Include the full transcript here, formatted as:]
[AI]: message
[Client]: message

---

*Generated by Voice Intake — [Date]*`;

async function generateBrief(session) {
  const conversation = session.conversationHistory.filter(m => m.role !== 'system');

  const transcript = conversation
    .map(m => `[${m.role === 'assistant' ? 'AI' : 'Client'}]: ${m.content}`)
    .join('\n');

  const userMessage = `Client name: ${session.clientName || 'Client'}
Date: ${new Date().toISOString().split('T')[0]}
Duration: ${Math.round((Date.now() - session.createdAt.getTime()) / 60000)} minutes
Turns: ${session.turnCount}

CONVERSATION TRANSCRIPT:
${transcript}`;

  return await llm.generateMarkdown(generationSystemPrompt, [{ role: 'user', content: userMessage }]);
}

module.exports = { generateBrief };
