const { questions } = require('../questions');

function buildMarkdown(session) {
  const a = (index) => session.answers[index]?.text || '_No answer provided_';
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  });

  // Extract client name from Q1 if possible
  const q1 = a(0);
  let clientName = 'Client';
  const nameMatch = q1.match(/(?:my name is|I'm|I am|this is)\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+)?)\b/);
  if (nameMatch) {
    clientName = nameMatch[1];
  }

  const durationMs = session.completedAt - session.createdAt;
  const durationMin = Math.round(durationMs / 60000);

  return `# Project Intake: ${clientName} — ${dateStr}

> Voice intake completed in ${durationMin} minute${durationMin !== 1 ? 's' : ''}

---

## FEATURE

### Vision
${a(0)}

### Problem & Users
${a(1)}

### Core Capabilities
${a(2)}

### User Journey
${a(3)}

---

## DESIGN & EXPERIENCE

### Look & Feel
${a(4)}

### User Flow Summary
${a(3)}

---

## DEPENDENCIES & INTEGRATIONS

### External Systems
${a(5)}

### Scale & Performance
${a(6)}

---

## OTHER CONSIDERATIONS
${a(7)}

---

## Raw Transcript

${questions.map((q, i) => `**Q${i + 1}: ${q.text}**\n${a(i)}`).join('\n\n')}

---

*Generated by Voice Intake — ${dateStr}*
`;
}

module.exports = { buildMarkdown };
